/// <reference lib="webworker" />
import { cleanupOutdatedCaches, precacheAndRoute } from "workbox-precaching";
import { clientsClaim } from "workbox-core";

declare const self: ServiceWorkerGlobalScope;

// Take control immediately
self.skipWaiting();
clientsClaim();

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST);
cleanupOutdatedCaches();

// Belt-and-suspenders cache nuke. cleanupOutdatedCaches() only removes
// the previous Workbox precache; it leaves any other caches alone (a
// prior deploy's runtime cache, an experimental cache name we tried
// once, anything left behind by extensions). On activate, drop every
// cache whose name doesn't match the current Workbox precache, so a
// new deploy always starts from clean storage.
self.addEventListener("activate", (event) => {
  event.waitUntil((async () => {
    const keys = await caches.keys();
    await Promise.all(
      keys
        .filter((k) => !k.startsWith("workbox-precache"))
        .map((k) => caches.delete(k))
    );
  })());
});

// ── Push notifications ────────────────────────────────────────────────────────
self.addEventListener("push", (event) => {
  const data = event.data?.json() ?? {};
  const title: string = data.title ?? "VenueFlow";
  const options: NotificationOptions = {
    body: data.body ?? "",
    icon: "/icons/icon.svg",
    badge: "/icons/badge.svg",
    tag: data.tag ?? "venueflow-notification",
    data: { url: data.url ?? "/" },
    requireInteraction: data.requireInteraction ?? false,
  };
  event.waitUntil(self.registration.showNotification(title, options));
});

// ── Notification click ────────────────────────────────────────────────────────
self.addEventListener("notificationclick", (event) => {
  event.notification.close();
  const url: string = event.notification.data?.url ?? "/";
  event.waitUntil(
    self.clients
      .matchAll({ type: "window", includeUncontrolled: true })
      .then((clientList) => {
        for (const client of clientList) {
          if (client.url.includes(url) && "focus" in client) return client.focus();
        }
        return self.clients.openWindow(url);
      })
  );
});
