import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import venuesRouter from "./venues";
import usersRouter from "./users";
import rolesRouter from "./roles";
import schedulesRouter from "./schedules";
import shiftsRouter from "./shifts";
import reservationsRouter from "./reservations";
import guestsRouter from "./guests";
import timeclockRouter from "./timeclock";
import floorplanRouter from "./floorplan";
import tippayrollRouter from "./tippayroll";
import messagingRouter from "./messaging";
import analyticsRouter from "./analytics";
import availabilityRouter from "./availability";
import pushRouter from "./push";
import integrationsRouter from "./integrations";
import reportsRouter from "./reports";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(venuesRouter);
router.use(usersRouter);
router.use(rolesRouter);
router.use(schedulesRouter);
router.use(shiftsRouter);
router.use(reservationsRouter);
router.use(guestsRouter);
router.use(timeclockRouter);
router.use(floorplanRouter);
router.use(tippayrollRouter);
router.use(messagingRouter);
router.use(analyticsRouter);
router.use(availabilityRouter);
router.use(pushRouter);
router.use(integrationsRouter);
router.use(reportsRouter);

export default router;
